In [1]:
import numpy as np
import itertools

In [2]:
PCNF = """c simple_v3_c2.cnf
c
p cnf 3 2
1 -3 0
2 3 -1 0"""

In [3]:
def eval_PL(PCNF, var):
    """
    Imput:
    - PCNF: PL in CNF
    - var: variable interpretation as an array
    
    Output:
    - Evaluation: True or false
    """
    # Get number of variable and condition
    for i in range(len(PCNF)):
        if PCNF[i:i+5]=="""p cnf""":
            # We use the structure to have access to what we need
            n = int(PCNF[i+6])
            c = int(PCNF[i+8])
            causes = PCNF[i+9:]
            
    # Get all causes    
    listofcauses = []
    for i in range (len(causes)):
        cause = []
        if causes[i:i+1]=='\n':
            j = 0
            while causes[i+j+1]!='0':
                j+=1
                if causes[i+j]!=' ':
                    cause.append(causes[i+j])
        if cause!=[]:            
            listofcauses.append(cause)
    

    # Create a validation matrix where each row is a cause and each column the variable state in this cause
    # -1:False, 1:True, 0: True or False
    
    val_matrix = np.zeros((c,n))
    
    for i in range (c):
        for j in range(len(listofcauses[i])):
            if listofcauses[i][j] == '-':
                val_matrix[i,int(listofcauses[i][j+1])-1] = -1
            elif listofcauses[i][j-1] != '-':
                val_matrix[i,int(listofcauses[i][j])-1] = 1
    
    # Checking the status
    
    status = True
    for i in range (c):
        if max(val_matrix[i]*var) != 1:
            status = False
    
    return(status)
        

In [4]:
def all_var(n):
    """
    Imput:
    - n : number of variables
    
    Output:
    - All possible combinations for n variables
    """
    return(np.array(list(map(list, itertools.product([-1, 1], repeat=n)))))
    

In [5]:
def decision_process(PCNF):
    """
    Imput:
    -PCNF: PL in CNF
    
    Output:
    -List of array: All possible combination for the PCNF
    """
    for i in range(len(PCNF)):
        if PCNF[i:i+5]=="""p cnf""":
            # We use the structure to have access to what we need
            n = int(PCNF[i+6])
    
    varset = all_var(n)
    
    lst=[]
    
    for v in varset:
        if eval_PL(PCNF, v):
            lst.append(v)
    
    return(lst)

In [6]:
# If we take the given PCNF example, we get all the possbile combination

decision_process(PCNF)

[array([-1, -1, -1]),
 array([-1,  1, -1]),
 array([ 1, -1,  1]),
 array([ 1,  1, -1]),
 array([1, 1, 1])]

In [49]:
# Here, we will take Alice, Benoıt, Christophe et David as 1 2 3 and 4 respectively

PCNF_Q1 = """c Q1.cnf
c
p cnf 4 4
-1 2 0
-2 -3 0
4 0
1 0"""

In [50]:

decision_process(PCNF_Q1)

[array([ 1,  1, -1,  1])]